### ISSUE TITLE
Sample projects did not run

### ISSUE THREAD

**Issue by mail2mhossain** [melihercan/WebRTCme#13]
Both Blazor projects failed to build and run

**Comment by melihercan** [comment]
I know it's the usual excuse, but I'm completely overloaded with commercial projects and don't have time, even on weekends, to add features, fix issues , or improve this project.
I'm hopeful that things will calm down in the next weeks so that I can deal with both requested and planned modifications.
But as far as I checked on the last commit blazor projects were all OK.
