### ISSUE TITLE
Can this be used outside of Xamarin/Blazor connection?

### ISSUE THREAD

**Issue by R00iBaard** [melihercan/WebRTCme#6]
Many thanks for this. 

Might be a silly question but is it possible to utilize this within my xamarin.forms application (client) yet communicate to an android device (server) that is not using Xamarin (or Blazor of course)? i.e. modify I believe the middleware to conform to these custom APIs?

**Comment by melihercan** [comment]
Hi there,
I am not very clear about your use case,  but here is what I understand from your description ( 2 use cases):

1.) You wanna use WebRTC (peer to peer) P2P connection between 2 mobile phones; one is using this WebRTCme framework (Xamarin) and the other one (an Android phone) using native WebRTC.  
WebRTC does not mandate any signaling protocol for initial connection setup, it is left to the vendors. So as long as these 2 parties can communicate through a signaling server, I don't see any issue for this use case. My middleware layer provides an implementation for signaling server and you can customize it the way you want, so that both Xamarin and Android phone can talk to each other.

2.) You mentioned client and server. As WebRTC is a peer to peer connection and there is no client/server concept. If you mean to use the Android phone as a signaling server, there is no issue on that as well.

Perhaps if you provide more details about your use case or requirements, I can elaborate more.

**Comment by R00iBaard** [comment]
Many many thanks for the detailed explanation. That was exactly what I was looking for. Still a webRTC noob, just been working with bluetooth low energy so my terminologies are all messed up :)
